services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_judge_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: online_judge_backend
    restart: always
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app_network
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    container_name: online_judge_frontend
    restart: always
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "8080:5173"
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # java-service:
  #   build: ./llm-gateway
  #   container_name: llmgateway
  #   restart: always
  #   depends_on:
  #     - backend
  #     - ollama
  #   networks:
  #     - app_network
  #   ports:
  #     - "8081:8081"
  #   env_file:
  #     - ./backend/.env

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_storage:/root/.ollama
  #     - ./ollama/online_judge_modelfile:/root/online_judge_modelfile
  #     - ./ollama/entrypoint.sh:/entrypoint.sh
  #   entrypoint: ["/entrypoint.sh"]
  #   networks:
  #     - app_network

  # redis:
  #   image: redis:alpine
  #   container_name: redis-dev
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app_network

networks:
  app_network:

volumes:
  db_data:
  # ollama_storage:
