services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: online_judge_backend
    restart: always
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    networks:
      - app_network
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    container_name: online_judge_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: online_judge_frontend
    restart: always
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "8080:5173"
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  microservice:
    build:
      context: ./llm-microservice
      dockerfile: Dockerfile
    container_name: online_judge_llm_microservice
    ports:
      - "8000:8000"
    volumes:
      - ./llm-microservice:/app
    command: python -m fastapi dev src/main.py --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
      - ./ollama/online_judge_chat_modelfile:/root/online_judge_chat_modelfile
      - ./ollama/online_judge_evaluation_modelfile:/root/online_judge_evaluation_modelfile
      - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
  ollama_storage:
