export enum CategoryEnum {
  BASICS = 'basics',
  DATA_STRUCTURES = 'data_structures',
  SORTING = 'sorting',
  SEARCH = 'search',
  TWO_POINTERS = 'two_pointers',
  GRAPH = 'graph',
  DYNAMIC_PROGRAMMING = 'dynamic_programming',
  GREEDY = 'greedy',
  BACKTRACKING = 'backtracking',
  MATH = 'math',
  STRINGS = 'strings',
  BIT_MANIPULATION = 'bit_manipulation',
  STACK = 'stack',
  HASHING = 'hashing',
  NUMBER_THEORY = 'number_theory',
  SLIDING_WINDOW = 'sliding_window',
  RECURSION = 'recursion',
  SIMULATION = 'simulation',
}
