export enum CategoryEnum {
  CONDITIONALS = 'conditionals',
  LOOPS = 'loops',
  BASIC_MATH = 'basic_math',
  STRINGS = 'strings',
  ARRAYS = 'arrays',
  COUNTING = 'counting',
  PATTERN_RECOGNITION = 'pattern_recognition',
  BASIC_OPTIMIZATION = 'basic_optimization',

  LINKED_LIST = 'linked_list',
  STACK = 'stack',
  QUEUE = 'queue',
  DEQUE = 'deque',
  TREE = 'tree',
  BINARY_SEARCH_TREE = 'binary_search_tree',
  HEAP = 'heap',
  GRAPH = 'graph',
  HASH_TABLE = 'hash_table',
  SET = 'set',
  UNION_FIND = 'union_find',
  SEGMENT_TREE = 'segment_tree',
  FENWICK_TREE = 'fenwick_tree',

  LINEAR_SEARCH = 'linear_search',
  BINARY_SEARCH = 'binary_search',
  SORTING = 'sorting',
  TWO_POINTERS = 'two_pointers',
  SLIDING_WINDOW = 'sliding_window',
  RECURSION = 'recursion',
  BACKTRACKING = 'backtracking',
  DYNAMIC_PROGRAMMING = 'dynamic_programming',
  BFS = 'bfs',
  DFS = 'dfs',
  DIJKSTRA = 'dijkstra',
  FLOYD_WARSHALL = 'floyd_warshall',
  GREEDY = 'greedy',
  DIVIDE_AND_CONQUER = 'divide_and_conquer',

  DECISION_PROBLEM = 'decision_problem',
  CONSTRUCTION_PROBLEM = 'construction_problem',
  OPTIMIZATION_PROBLEM = 'optimization_problem',
  COUNTING_PROBLEM = 'counting_problem',
  SEARCH_PROBLEM = 'search_problem',

  OOP = 'oop',
}
